services:
  lidar-tool:
    build: .
    image: lidar-gcp-pipeline:latest
    volumes:
      - .:/project
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/project/key.json  # Opcional: si tienes una key.json local
    working_dir: /project
    command: python3 src/lidar_worker.py --help
